name: Publish to edge

on:
  push:
    branches:
      - main
      - track/*

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@main
    permissions:
      contents: write
      packages: write
      actions: read
    secrets: inherit

  secscan:
    needs: publish-to-edge
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
    uses: ./.github/workflows/secscan.yaml # zizmor: ignore[self-repository]
